---
- name: Deploy Application to VM2
  hosts: vm2
  become: yes
  become_method: sudo
  tasks:

    # 0. Ensure required dependencies are present
    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3
        state: present
        update_cache: yes

    # 1. Add Docker's official GPG key
    - name: Add Docker’s official GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    # 2. Set up Docker repository
    - name: Add Docker repository
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    # 3. Install Docker and Compose v2 plugin
    - name: Install Docker CE and Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes


    # 4. Ensure Docker service is running
    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy docker-compose.yml to VM2
      copy:
        src: /var/lib/jenkins/workspace/pfa-deploy/projetPfa/docker-compose.yml
        dest: /home/aymen/projects/dreamsport/docker-compose.yml
        owner: aymen
        group: aymen
        mode: '0644'

    # 5. Pull Docker images defined in the Docker Compose file
    - name: Pull all Docker images in the Docker Compose file
      shell: docker compose -f docker-compose.yml pull
      args:
        chdir: /home/aymen/projects/dreamsport

    - name: Stop and remove existing Docker Compose containers
      docker_compose:
        project_src: /home/aymen/projects/dreamsport
        state: absent


    # 6. Start Docker containers using Compose
    - name: Start Docker containers
      docker_compose:
        project_src: /home/aymen/projects/dreamsport
        state: present
        restarted: yes

    # 7. Install Nginx
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    # 8. Copy Angular build files to Nginx serving directory
    - name: Copy Angular build files to VM2
      copy:
        src: /var/lib/jenkins/workspace/pfa-deploy/projetPfa/angular/dist/dreams-sports
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'

    # 9. Configure Nginx to serve frontend
    - name: Configure Nginx to serve frontend
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    # 10. Restart Nginx
    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted
        enabled: yes
